export const organizationdata = [
{
    id: 1,
    name: "EplusApp",
    brand: "d1",
    tinNumber: 1334345,
    address: "Addis Ababa",
    type: "plc",
    streetNumber: "kerfhk",
    digitalID: "1084514",
    businessSector: "software development",
    bank: "rg4",
    numberOfStocks: 45,
    userId: 3,
    orgUsers: 3,
    email: "Eplusapp.et",
    logo: "promotion-lg.png",
    establishment: "2023-01-31",
    capital: "100",
    employees: 50,
    currentCapital: "34",
    stockFounder: 15,
    currentStock: 5000,
    country: "Ethiopia",
    region: "Amhara",
    zone: "Bahirdar",
    woreda: "Bahirdar",
    kebele: "14",
    city: "bahirdar",
    subCity: "tana",
    houseNumber: "",
    forPromotion: true,
    audio: null,
    video: null,
    createdAt: "2023-10-13T13:28:43.000Z",
    updatedAt: "2023-10-18T01:58:36.000Z",
    Legality: null,
    day_work:[ 
      
      {
      id:3,
      name:"promotion webSite",
      brand:"WS",
      model:"01WS",
      title:"Vacancy",
      type:"Vacancy",
      engine:null,
      process_time:null,
      weight:null,
      version:null,
      ram:null,
      generation:null,
      material:null,
      quality:null,
      quantity:1,
      price:"1000000",
      featureImage:"promotion-lg.png",
      audio:null,
      video:null,
      description:"ይህ ኢጵላሣጵ ዌብ ሳይት ነው ኢጵላሣጵ የራሱ የሆነ ዌብሳይት አልምቶ አሁን ደሞ ለግለሰቦች እና ለድርጅቶች የየራሳቸው የሆነ ዌብሳይት ለማልማት ሙሉ ዝግጅቱን ጨርሷል። እርሶም እድሉን ይጠቀሙ።",
      specification:"[]",
      categoryId:1,
      categoryName:"electronics",
      forSale:true,
      userId:3,
      orgId:3,
      forPromotion:true,
      createdAt:"2023-10-02T16:11:38.000Z",
      updatedAt:"2023-10-03T13:24:13.000Z"
    },
    {
      id:3,
      name:"promotion webSite",
      brand:"Bs",
      title:"vacancy",
      type:"Vacancy",
      model:"01Bs",
      size:null,
      thickness:null,
      engine:null,
      process_time:null,
      weight:null,
      version:null,
      ram:null,
      generation:null,
      material:null,
      quality:null,
      quantity:1,
      price:"100000",
      featureImage:"hero.jpeg",
      audio:null,
      video:null,
      description:"yes yesnow seethis.ይህ ኢጵላሣጵ ዌብ ሳይት ነው ኢጵላሣጵ የራሱ የሆነ ዌብሳይት አልምቶ አሁን ደሞ ለግለሰቦች እና ለድርጅቶች የየራሳቸው የሆነ ዌብሳይት ለማልማት ሙሉ ዝግጅቱን ጨርሷል። እርሶም እድሉን ይጠቀሙ።",
      specification:"[]",
      categoryId:1,
      categoryName:"electronics",
      forSale:true,
      userId:4,
      orgId:4,
      forPromotion:true,
      createdAt:"2023-11-02T16:11:38.000Z",
      updatedAt:"2023-11-03T13:24:13.000Z"
    },
    {id:5,
    shortCode:"35186",
    title:"የቀን ስራ",
    type:"daily_work",
    address:"ባዳ",
    featureImage:"telegramecomerece.jpg",
    description:"Position 1: Accountant (IFRS \n Certified )\nPosition 2: Research Officer Position 3:Electro Mechanical  \n DesignerPosition 4: ArchitectPosition 5: IT (software ስልጠና \n  ዶክሜንቴሽ)Position 6: Digital Business   \n Innovation Officer Position 7: Cloud and Core  \n Systems Engineer Position 8: Project ManagerPosition 9:Graphic Designer",
    openingDate:"2023-10-02T00:00:00.000Z",
    closingDate:"2023-12-02T00:00:00.000Z",
    image:"Loading......",
    video:null,
    audio:null,
    price:null,
    userId:3,
    orgId:3,
    createdAt:"2023-10-02T16:19:11.000Z",
    updatedAt:"2023-10-02T16:19:11.000Z"
  }],
    job_vacancies:[
        {
            id:3,
            name:"promotion webSite",
            brand:"WS",
            model:"01WS",
            title:"Vacancy",
            type:"Vacancy",
            engine:null,
            process_time:null,
            weight:null,
            version:null,
            ram:null,
            generation:null,
            material:null,
            quality:null,
            quantity:1,
            price:"1000000",
            featureImage:"promotion-lg.png",
            audio:null,
            video:null,
            description:"ይህ ኢጵላሣጵ ዌብ ሳይት ነው ኢጵላሣጵ የራሱ የሆነ ዌብሳይት አልምቶ አሁን ደሞ ለግለሰቦች እና ለድርጅቶች የየራሳቸው የሆነ ዌብሳይት ለማልማት ሙሉ ዝግጅቱን ጨርሷል። እርሶም እድሉን ይጠቀሙ።",
            specification:"[]",
            categoryId:1,
            categoryName:"electronics",
            forSale:true,
            userId:3,
            orgId:3,
            forPromotion:true,
            createdAt:"2023-10-02T16:11:38.000Z",
            updatedAt:"2023-10-03T13:24:13.000Z"
          },
          {
            id:3,
            name:"promotion webSite",
            brand:"Bs",
            title:"vacancy",
            type:"Vacancy",
            model:"01Bs",
            size:null,
            thickness:null,
            engine:null,
            process_time:null,
            weight:null,
            version:null,
            ram:null,
            generation:null,
            material:null,
            quality:null,
            quantity:1,
            price:"100000",
            featureImage:"hero.jpeg",
            audio:null,
            video:null,
            description:"yes yesnow seethis.ይህ ኢጵላሣጵ ዌብ ሳይት ነው ኢጵላሣጵ የራሱ የሆነ ዌብሳይት አልምቶ አሁን ደሞ ለግለሰቦች እና ለድርጅቶች የየራሳቸው የሆነ ዌብሳይት ለማልማት ሙሉ ዝግጅቱን ጨርሷል። እርሶም እድሉን ይጠቀሙ።",
            specification:"[]",
            categoryId:1,
            categoryName:"electronics",
            forSale:true,
            userId:4,
            orgId:4,
            forPromotion:true,
            createdAt:"2023-11-02T16:11:38.000Z",
            updatedAt:"2023-11-03T13:24:13.000Z"
          },
          {id:5,
          shortCode:"35186",
          title:"የቀን ስራ",
          type:"daily_work",
          address:"ባዳ",
          featureImage:"telegramecomerece.jpg",
          description:"Position 1: Accountant (IFRS \n Certified )\nPosition 2: Research Officer Position 3:Electro Mechanical  \n DesignerPosition 4: ArchitectPosition 5: IT (software ስልጠና \n  ዶክሜንቴሽ)Position 6: Digital Business   \n Innovation Officer Position 7: Cloud and Core  \n Systems Engineer Position 8: Project ManagerPosition 9:Graphic Designer",
          openingDate:"2023-10-02T00:00:00.000Z",
          closingDate:"2023-12-02T00:00:00.000Z",
          image:"Loading......",
          video:null,
          audio:null,
          price:null,
          userId:3,
          orgId:3,
          createdAt:"2023-10-02T16:19:11.000Z",
          updatedAt:"2023-10-02T16:19:11.000Z"
        },
    ],

    Products: [
     {
            id: 1,
            name: "EplusApp",
            brand: "building",
            model: "01",
            size: null,
            thickness: null,
            engine: null,
            process_time: null,
            weight: null,
            version: null,
            ram: null,
            generation: null,
            material: null,
            quality: null,
            quantity: 1,
            price: "5000000",
            featureImage: "telegrameplusapp.jpg",
            audio: null,
            video: null,
            description: "a very amazing and peaceful building that is located in an amazing place bahirdar. come and buy",
            specification: "[]",
            categoryId: 2,
            categoryName: "softawre",
            forSale: true,
            userId: 3,
            orgId: 1,
            forPromotion: true,
            createdAt: "2023-10-14T08:40:42.000Z",
            updatedAt: "2023-10-19T08:20:15.000Z"
        },
        {
            id: 2,
            name: "promotoion ",
            brand: "software",
            model: "web",
            size: null,
            thickness: null,
            engine: null,
            process_time: null,
            weight: null,
            version: null,
            ram: null,
            generation: null,
            material: null,
            quality: null,
            quantity: 2,
            price: "4000",
            featureImage: "image_2023-06-10_17-03-58.png",
            audio: "1697280968-yo and stota 2.mp3",
            video: "1697280979-yo and stota 2.mp3",
            description: "a software that will enable users to create their website",
            specification: "[]",
            categoryId: 2,
            categoryName: "softawre",
            forSale: false,
            userId: 3,
            orgId: 1,
            forPromotion: true,
            createdAt: "2023-10-14T10:58:30.000Z",
            updatedAt: "2023-10-19T08:20:19.000Z"
        },
        {
          id: 2,
          name: "promotoion ",
          brand: "software",
          model: "web",
          size: null,
          thickness: null,
          engine: null,
          process_time: null,
          weight: null,
          version: null,
          ram: null,
          generation: null,
          material: null,
          quality: null,
          quantity: 2,
          price: "4000",
          featureImage: "photo_2023-07-19_17-02-39.jpg",
          audio: "1697280968-yo and stota 2.mp3",
          video: "1697280979-yo and stota 2.mp3",
          description: "a software that will enable users to create their website",
          specification: "[]",
          categoryId: 2,
          categoryName: "softawre",
          forSale: false,
          userId: 3,
          orgId: 1,
          forPromotion: true,
          createdAt: "2023-10-14T10:58:30.000Z",
          updatedAt: "2023-10-19T08:20:19.000Z"
      }
    ],
    bids:[
        {
            id:3,
            name:"promotion webSite",
            brand:"Bs",
            title:"vacancy",
            type:"Vacancy",
            model:"01Bs",
            size:null,
            thickness:null,
            engine:null,
            process_time:null,
            weight:null,
            version:null,
            ram:null,
            generation:null,
            material:null,
            quality:null,
            quantity:1,
            price:"100000",
            featureImage:"hero.jpeg",
            audio:null,
            video:null,
            description:"yes yesnow seethis.ይህ ኢጵላሣጵ ዌብ ሳይት ነው ኢጵላሣጵ የራሱ የሆነ ዌብሳይት አልምቶ አሁን ደሞ ለግለሰቦች እና ለድርጅቶች የየራሳቸው የሆነ ዌብሳይት ለማልማት ሙሉ ዝግጅቱን ጨርሷል። እርሶም እድሉን ይጠቀሙ።",
            specification:"[]",
            categoryId:1,
            categoryName:"electronics",
            forSale:true,
            userId:4,
            orgId:4,
            forPromotion:true,
            createdAt:"2023-11-02T16:11:38.000Z",
            updatedAt:"2023-11-03T13:24:13.000Z"
          },
          {id:5,
          shortCode:"35186",
          title:"የቀን ስራ",
          type:"daily_work",
          address:"ባዳ",
          featureImage:"telegramecomerece.jpg",
          description:"Position 1: Accountant (IFRS \n Certified )\nPosition 2: Research Officer Position 3:Electro Mechanical  \n DesignerPosition 4: ArchitectPosition 5: IT (software ስልጠና \n  ዶክሜንቴሽ)Position 6: Digital Business   \n Innovation Officer Position 7: Cloud and Core  \n Systems Engineer Position 8: Project ManagerPosition 9:Graphic Designer",
          openingDate:"2023-10-02T00:00:00.000Z",
          closingDate:"2023-12-02T00:00:00.000Z",
          image:"Loading......",
          video:null,
          audio:null,
          price:null,
          userId:3,
          orgId:3,
          createdAt:"2023-10-02T16:19:11.000Z",
          updatedAt:"2023-10-02T16:19:11.000Z"
        },
        {id:5,
          shortCode:"35186",
          title:"የቀን ስራ",
          type:"daily_work",
          address:"ባዳ",
          featureImage:"telegramecomerece.jpg",
          description:"Position 1: Accountant (IFRS \n Certified )\nPosition 2: Research Officer Position 3:Electro Mechanical  \n DesignerPosition 4: ArchitectPosition 5: IT (software ስልጠና \n  ዶክሜንቴሽ)Position 6: Digital Business   \n Innovation Officer Position 7: Cloud and Core  \n Systems Engineer Position 8: Project ManagerPosition 9:Graphic Designer",
          openingDate:"2023-10-02T00:00:00.000Z",
          closingDate:"2023-12-02T00:00:00.000Z",
          image:"Loading......",
          video:null,
          audio:null,
          price:null,
          userId:3,
          orgId:3,
          createdAt:"2023-10-02T16:19:11.000Z",
          updatedAt:"2023-10-02T16:19:11.000Z"
        }
    ],
    Plan: null,
    Property: null,
    Training: null,
    Hasab: null,
    Projectoffice: null,
    Promotion: null,
    Tef_Wof: null,
    Jobskill: null,
    Users: [
        {
            id: 3,
            firstName: "Estifanos",
            middleName: "Abebaw",
            lastName: "teshome",
            email: "tekle.estifanos.17@gmail.com",
            password: "$2b$10$PoBHXnYb5RmKPlz02iIJm.TS2o7klMJlGAp39jSJverXPpGLi91b2",
            sex: "ሴት",
            userCode: 816494,
            role: "admin",
            dateOfBirth: "2023-12-31",
            phoneNumber: "09417789264",
            kebele: "01",
            subCity: "Addis Ababa",
            city: "Addis Ababa",
            region: "Addis Ababa",
            country: "Addis Ababa, Ethiopia",
            continent: "Africa",
            religion: "ORTHODOX",
            position: "ebf",
            latitude: "9",
            longitude: "39",
            privateData: "{\"phoneNumber\":true,\"email\":true}",
            education: "brwt",
            profession: "rhtr",
            avatar: "1697268425-20230919_150457.jpg",
            maritalStatus: "ያላገባ",
            bank: "fvkdfjv",
            bankAccountNumber: "dfvgduyfh",
            workExperience: "",
            achievement: "rgtr",
            skill: "frt",
            hobbies: "ergrt",
            weight: "1",
            hight: "1",
            language: "amharic",
            bloodType: "B",
            eyeColor: "er",
            motherName: "zufan",
            motherlastName: "kiflu",
            positionId: 1,
            orgId: 1,
            createdAt: "2023-10-13T13:10:22.000Z",
            updatedAt: "2023-10-18T02:06:45.000Z"
        }
    ]
}
];